import "server-only";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import SupabaseAuthProvider from "@/components/providers/supabase-auth-provider";
import SupabaseProvider from "@/components/providers/supabase-provider";
import { createClient } from "@/utils/supabase-server";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();
  return (
    <html lang="en">
      <SupabaseProvider>
        <SupabaseAuthProvider serverSession={session}>
          <body className={inter.className}>{children}</body>
        </SupabaseAuthProvider>
      </SupabaseProvider>
    </html>
  );
}
